### ISSUE TITLE
Build 2 versions of Roadie container -- with and without scripts

### ISSUE THREAD

**Issue by jmuhlich** [labsyspharm/mcmicro#400] opened 2022-06-08 18:03 UTC
This is a proposal for setting up two different Roadie container builds:

1. Just Python and the script dependencies (same as the current container)
2. All of the above, but also including the scripts

Build 2 would be useful as a standalone container (outside of mcmicro/nextflow), but it would change more often as the scripts are modified and added to. Build 1 would remain for use with mcmicro and not change much. We could keep everything under the same base `roadie` container name and distinguish the builds via tags.

### A -- Dependencies-only as primary
1. `roadie:YYYY-MM-DD`
2. `roadie:YYYY-MM-DD-full`

### B -- Scripts-included as primary
1. `roadie:YYYY-MM-DD-slim`
2. `roadie:YYYY-MM-DD`

### C -- Equal standing
1. `roadie:YYYY-MM-DD-slim`
2. `roadie:YYYY-MM-DD-full`

I am open to alternative names for the `-full` or `-slim` suffixes, but do I think they should be suffixes and not prefixes (I took inspiration from the debian containers' `-slim` suffix here).

## Open questions

1. Should the "slim" image be re-tagged every time the "full" image is updated, even though the slim image itself didn't change?
2. Which build should receive the `latest` tag?

**Comment by ArtemSokolov** [comment] 2023-01-02 05:27
Going to close this, because I think this is unnecessary complexity.
Roadie behavior can be easily reproduced in any environment just by mounting the scripts alongside the data:

```
git clone https://github.com/labsyspharm/mcmicro
docker run -it -v "$PWD"/mcmicro/roadie/scripts:/app -v /path/to/data:/data labsyspharm/roadie:2022-10-20 /bin/bash
```

All scripts are then available under `/app` inside containers, e.g., `python /app/pyramidize.py --help`.

**Closed as completed by ArtemSokolov** 2023-01-02 05:27 UTC
Labels: enhancement, roadie
