### ISSUE TITLE
`unmicst (3)` terminated with an error exit status (137)

### ISSUE THREAD

**Issue by edn314** [labsyspharm/mcmicro#47] opened 2020-03-18 20:44 UTC
@clarenceyapp When running on my local machine, I come across the following error for exemplar-002.  I am passing the --skip_ashlar and --TMA options. 
```
Error executing process > 'unmicst (3)'

Caused by:
  Process `unmicst (3)` terminated with an error exit status (137)

Command executed:

  python /app/UnMicst.py 3.tif --outputPath .

Command exit status:
  137

Command output:
  (empty)

Command error:
  WARNING:tensorflow:From /app/UnMicst.py:70: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

  WARNING:tensorflow:From /app/UnMicst.py:103: The name tf.truncated_normal is deprecated. Please use tf.random.truncated_normal instead.

  WARNING:tensorflow:From /app/UnMicst.py:93: batch_normalization (from tensorflow.python.layers.normalization) is deprecated and will be removed in a future version.
  Instructions for updating:
  Use keras.layers.BatchNormalization instead.  In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.batch_normalization` documentation).
  WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/layers/normalization.py:327: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
  Instructions for updating:
  Please use `layer.__call__` method instead.
  WARNING:tensorflow:From /app/UnMicst.py:95: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.

  WARNING:tensorflow:From /app/UnMicst.py:500: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

  WARNING:tensorflow:From /app/UnMicst.py:501: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

  WARNING:tensorflow:From /app/UnMicst.py:501: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

  2020-03-18 20:21:04.025969: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
  2020-03-18 20:21:04.034270: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2304000000 Hz
  2020-03-18 20:21:04.036688: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x3ed6990 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
  2020-03-18 20:21:04.036767: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
  2020-03-18 20:21:04.038970: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
  2020-03-18 20:21:04.039374: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: UNKNOWN ERROR (303)
  2020-03-18 20:21:04.039448: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (da7cf1d85f76): /proc/driver/nvidia/version does not exist
  .command.sh: line 2:     6 Killed                  python /app/UnMicst.py 3.tif --outputPath .
```

**Comment by ArtemSokolov** [comment] 2020-03-18 20:52
That looks like a CUDA drivers issue.

**Comment by clarenceyapp** [comment] 2020-03-18 20:52
@edn314 How are you running UnMicst? Is it through nextflow? If not, are you using the docker container or the Python code directly?

**Comment by clarenceyapp** [comment] 2020-03-18 20:53
@ArtemSokolov if edn314 is using the docker container, should there still be CUDA driver issues? I thought everything should be packaged inside right?

**Comment by ArtemSokolov** [comment] 2020-03-18 20:55
Tensorflow-based containers attempt to make use of shared resources (such as GPU) in the host machine: https://www.tensorflow.org/install/docker

**Comment by clarenceyapp** [comment] 2020-03-18 20:57
Looking at the error messages, it looks like it's not using the GPU though otherwise it would have flagged the GPU model in the warning messages. Is the CPU version used by default in the pipeline?

**Comment by ArtemSokolov** [comment] 2020-03-18 21:25
Edward notes that the issue exists only for exemplar-002. Exemplar-001 runs end-to-end without issues.

We confirmed that Edward is able to instantiate a `labsyspharm/unmicst:latest` container and that it's working with a simple `python -c "import tensorflow as tf; print(tf.reduce_sum(tf.random.normal([1000, 1000])))"` test. We also confirmed that the container is missing `/proc/driver/nvidia`, which is consistent with the error observed.

The hypothesis is that UnMicst is attempting to force GPU usage in a portion of the code that gets invoked during exemplar-002 processing. This is causing Tensorflow to look for CUDA drivers, even though the container was built on a CPU-only TF base.

Issue observed on macOS Mojave 10.14.6

**Comment by ArtemSokolov** [comment] 2020-03-19 18:37
Exit code 137 is Docker running out of memory.
Issue is easily fixed by increasing the allowable limit:
https://docs.docker.com/docker-for-mac/images/menu/prefs-advanced.png

**Closed as completed by ArtemSokolov** 2020-03-19 18:37 UTC

**Comment by LibbyLi667** [comment] 2022-07-11 04:57
> Exit code 137 is Docker running out of memory. Issue is easily fixed by increasing the allowable limit: https://docs.docker.com/docker-for-mac/images/menu/prefs-advanced.png

Hi there,

Anyone could help? I got this error:
```
executor >  local (1)
[-        ] process > illumination           -
[69/0f1e83] process > registration:ashlar    [  0%] 0 of 1
executor >  local (1)
[-        ] process > illumination           -
[69/0f1e83] process > registration:ashlar    [100%] 1 of 1, failed: 1 ✘
[-        ] process > dearray:coreograph     -
[-        ] process > segmentation:worker    -
[-        ] process > segmentation:s3seg     -
[-        ] process > quantification:mcquant -
[-        ] process > cellstates:worker      -
[-        ] process > viz:roadie:runTask     -
[-        ] process > viz:autominerva        -
Error executing process > 'registration:ashlar'

Caused by:
  Process `registration:ashlar` terminated with an error exit status (137)

Command executed:

  ashlar 'R1 CD68.tif' 'R1 DAPI.tif' 'R1 HLADR.tif' 'R1 IBA1.tif' 'R1 LFERRITIN.tif' 'R1 PDGFRB.tif' 'R2 DAPI.tif' 'R2 FOXP2.tif' 'R2 MAP2.tif' 'R2 NECAB1.tif' 'R2 NEUN.tif' 'R2 PCP4.tif'  -m 30        -o AZ135_test.ome.tif

Command exit status:
  137

Command output:
  Stitching and registering input images
  Cycle 0:
      reading R1 CD68.tif
  
      assembling thumbnail 1/1
  
  Cycle 1:
      reading R1 DAPI.tif
  
      assembling thumbnail 1/1
  
      estimated cycle offset [y x] = [-57.  -2.]
  
      aligning tile 1/1

Command error:
  WARNING: Stage coordinates undefined; falling back to (0, 0).
  WARNING: Stage coordinates undefined; falling back to (0, 0).
  .command.sh: line 2:     7 Killed                  ashlar 'R1 CD68.tif' 'R1 DAPI.tif' 'R1 HLADR.tif' 'R1 IBA1.tif' 'R1 LFERRITIN.tif' 'R1 PDGFRB.tif' 'R2 DAPI.tif' 'R2 FOXP2.tif' 'R2 MAP2.tif' 'R2 NECAB1.tif' 'R2 NEUN.tif' 'R2 PCP4.tif' -m 30 -o AZ135_test.ome.tif

```

Is this caused by docker running out of memory? The page seems not working now.

Cheers,
Libby

**Comment by ArtemSokolov** [comment] 2022-07-11 13:59
Hi Libby,

Yes, exit code `137` together with a `Killed` message usually indicates an out-of-memory error. If you're running the pipeline on a Mac, there is a Docker setting (https://docs.docker.com/desktop/mac/#resources) to increase available Memory.

On newer Macs, you may also run into issues with downstream modules (https://github.com/labsyspharm/mcmicro/issues/353#issuecomment-1047934907). Unfortunately, we're still waiting on GitHub Actions to implement https://github.com/actions/virtual-environments/issues/2187, which would then allow us to address the issue on our end.

**Comment by LibbyLi667** [comment] 2022-07-12 21:55
Hi Artem,

I tried on a linux server but encountered the same error. 
```
$ nextflow run labsyspharm/mcmicro --in AZ135/ --probability-maps ilastik
N E X T F L O W  ~  version 22.04.4
Launching `https://github.com/labsyspharm/mcmicro` [cheeky_kalam] DSL2 - revision: c52e85a923 [master]
executor >local (1)
[-        ] process > illumination           -
[f5/2c6e29] process > registration:ashlar    [  0%] 0 of 1
[-        ] process > dearray:coreograph     -
[-        ] process > segmentation:worker    -
[-        ] process > segmentation:s3seg     -
[-        ] process > quantification:mcquant -
[-        ] process > cellstates:worker      -
executor >  local (1)
[-        ] process > illumination           -
[f5/2c6e29] process > registration:ashlar    [100%] 1 of 1, failed: 1 ✘
[-        ] process > dearray:coreograph     -
[-        ] process > segmentation:worker    -
[-        ] process > segmentation:s3seg     -
[-        ] process > quantification:mcquant -
[-        ] process > cellstates:worker      -
[-        ] process > viz:roadie:runTask     -
[-        ] process > viz:autominerva        -
Error executing process > 'registration:ashlar'

Caused by:
  Process `registration:ashlar` terminated with an error exit status (137)

Command executed:

  ashlar 'R1 CD68.tif' 'R1 DAPI.tif' 'R1 HLADR.tif' 'R1 IBA1.tif' 'R1 LFERRITIN.tif' 'R1 PDGFRB.tif' 'R2 DAPI.tif' 'R2 FOXP2.tif' 'R2 MAP2.tif' 'R2 NECAB1.tif' 'R2 NEUN.tif' 'R2 PCP4.tif' 'R3 CALBINDIN.tif' 'R3 CALRETININ.tif' 'R3 DAPI.tif' 'R3 HISTONES.tif' 'R3 PARVALBUMIN.tif' 'R3 SOMATOSTATIN.tif' 'R4 CNPASE.tif' 'R4 DAPI.tif' 'R4 MBP.tif' 'R4 PERK.tif' 'R4 UBIQUITIN.tif' 'R5 AQUAPORIN 4.tif' 'R5 DAPI.tif' 'R5 NFH.tif' 'R5 NFL.tif' 'R5 NFM.tif' 'R6 COLLAGEN IV.tif' 'R6 DAPI.tif' 'R6 FIBRINOGEN.tif' 'R6 GAD.tif' 'R6 SMA.tif' 'R7 DAPI.tif' 'R7 GFAP.tif' 'R7 NFM.tif' 'R7 PAN TDP43.tif' 'R7 PHOSPHO TDP43.tif' 'R7 UEA LECTIN.tif' 'R8 3R TAU.tif' 'R8 4R TAU.tif' 'R8 AT8 TAU.tif' 'R8 BETA AMYLOID.tif' 'R8 DAPI.tif' 'R8 PHOSPHO ALPHA SYNUCLEIN.tif'  -m 30        -o AZ135.ome.tif

Command exit status:
  137

Command output:
  Stitching and registering input images
  Cycle 0:
      reading R1 CD68.tif
  
      assembling thumbnail 1/1
  
  Cycle 1:
      reading R1 DAPI.tif
  
      assembling thumbnail 1/1
  
      estimated cycle offset [y x] = [-57.  -2.]
  
      aligning tile 1/1

Command error:
  WARNING: Stage coordinates undefined; falling back to (0, 0).
  WARNING: Stage coordinates undefined; falling back to (0, 0).
  .command.sh: line 2:     6 Killed                  ashlar 'R1 CD68.tif' 'R1 DAPI.tif' 'R1 HLADR.tif' 'R1 IBA1.tif' 'R1 LFERRITIN.tif' 'R1 PDGFRB.tif' 'R2 DAPI.tif' 'R2 FOXP2.tif' 'R2 MAP2.tif' 'R2 NECAB1.tif' 'R2 NEUN.tif' 'R2 PCP4.tif' 'R3 CALBINDIN.tif' 'R3 CALRETININ.tif' 'R3 DAPI.tif' 'R3 HISTONES.tif' 'R3 PARVALBUMIN.tif' 'R3 SOMATOSTATIN.tif' 'R4 CNPASE.tif' 'R4 DAPI.tif' 'R4 MBP.tif' 'R4 PERK.tif' 'R4 UBIQUITIN.tif' 'R5 AQUAPORIN 4.tif' 'R5 DAPI.tif' 'R5 NFH.tif' 'R5 NFL.tif' 'R5 NFM.tif' 'R6 COLLAGEN IV.tif' 'R6 DAPI.tif' 'R6 FIBRINOGEN.tif' 'R6 GAD.tif' 'R6 SMA.tif' 'R7 DAPI.tif' 'R7 GFAP.tif' 'R7 NFM.tif' 'R7 PAN TDP43.tif' 'R7 PHOSPHO TDP43.tif' 'R7 UEA LECTIN.tif' 'R8 3R TAU.tif' 'R8 4R TAU.tif' 'R8 AT8 TAU.tif' 'R8 BETA AMYLOID.tif' 'R8 DAPI.tif' 'R8 PHOSPHO ALPHA SYNUCLEIN.tif' -m 30 -o AZ135.ome.tif

Work dir:
  /mnt/MCM/work/f5/2c6e29edaedd1a2cbd91f42e734a37

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
```

**Comment by ArtemSokolov** [comment] 2022-07-12 22:11
Hi Libby, there should be a `.command.log` in `/mnt/MCM/work/f5/2c6e29edaedd1a2cbd91f42e734a37`.
Does it provide any additional information?

**Comment by LibbyLi667** [comment] 2022-07-12 22:41
/mnt/MCM$ ls work/f5/2c6e29edaedd1a2cbd91f42e734a37/
R1 CD68.tif       R1 PDGFRB.tif  R2 NEUN.tif        R3 HISTONES.tif      R4 MBP.tif          R5 NFH.tif          R6 FIBRINOGEN.tif  R7 NFM.tif            R8 4R TAU.tif
R1 DAPI.tif       R2 DAPI.tif    R2 PCP4.tif        R3 PARVALBUMIN.tif   R4 PERK.tif         R5 NFL.tif          R6 GAD.tif         R7 PAN TDP43.tif      R8 AT8 TAU.tif
R1 HLADR.tif      R2 FOXP2.tif   R3 CALBINDIN.tif   R3 SOMATOSTATIN.tif  R4 UBIQUITIN.tif    R5 NFM.tif          R6 SMA.tif         R7 PHOSPHO TDP43.tif  R8 BETA AMYLOID.tif
R1 IBA1.tif       R2 MAP2.tif    R3 CALRETININ.tif  R4 CNPASE.tif        R5 AQUAPORIN 4.tif  R6 COLLAGEN IV.tif  R7 DAPI.tif        R7 UEA LECTIN.tif     R8 DAPI.tif
R1 LFERRITIN.tif  R2 NECAB1.tif  R3 DAPI.tif        R4 DAPI.tif          R5 DAPI.tif         R6 DAPI.tif         R7 GFAP.tif        R8 3R TAU.tif         R8 PHOSPHO ALPHA SYNUCLEIN.tif

**Comment by ArtemSokolov** [comment] 2022-07-12 23:10
Files that begin with `.` are "hidden" on linux. Try `ls -a work/f5/2c6e29edaedd1a2cbd91f42e734a37/` to see all files in the directory and `cat work/f5/2c6e29edaedd1a2cbd91f42e734a37/.command.log` to view the contents of the log.

**Comment by LibbyLi667** [comment] 2022-07-13 03:57
That's the log file: 
$ cat work/f5/2c6e29edaedd1a2cbd91f42e734a37/.command.log
WARNING: Stage coordinates undefined; falling back to (0, 0).
Stitching and registering input images
Cycle 0:
    reading R1 CD68.tif
    assembling thumbnail 1/1WARNING: Stage coordinates undefined; falling back to (0, 0).


Cycle 1:
    reading R1 DAPI.tif
    assembling thumbnail 1/1
    estimated cycle offset [y x] = [-57.  -2.]
    aligning tile 1/1/mnt/MCM/work/f5/2c6e29edaedd1a2cbd91f42e734a37/.command.sh: line 2:     6 Killed                  ashlar 'R1 CD68.tif' 'R1 DAPI.tif' 'R1 HLADR.tif' 'R1 IBA1.tif' 'R1 LFERRITIN.tif' 'R1 PDGFRB.tif' 'R2 DAPI.tif' 'R2 FOXP2.tif' 'R2 MAP2.tif' 'R2 NECAB1.tif' 'R2 NEUN.tif' 'R2 PCP4.tif' 'R3 CALBINDIN.tif' 'R3 CALRETININ.tif' 'R3 DAPI.tif' 'R3 HISTONES.tif' 'R3 PARVALBUMIN.tif' 'R3 SOMATOSTATIN.tif' 'R4 CNPASE.tif' 'R4 DAPI.tif' 'R4 MBP.tif' 'R4 PERK.tif' 'R4 UBIQUITIN.tif' 'R5 AQUAPORIN 4.tif' 'R5 DAPI.tif' 'R5 NFH.tif' 'R5 NFL.tif' 'R5 NFM.tif' 'R6 COLLAGEN IV.tif' 'R6 DAPI.tif' 'R6 FIBRINOGEN.tif' 'R6 GAD.tif' 'R6 SMA.tif' 'R7 DAPI.tif' 'R7 GFAP.tif' 'R7 NFM.tif' 'R7 PAN TDP43.tif' 'R7 PHOSPHO TDP43.tif' 'R7 UEA LECTIN.tif' 'R8 3R TAU.tif' 'R8 4R TAU.tif' 'R8 AT8 TAU.tif' 'R8 BETA AMYLOID.tif' 'R8 DAPI.tif' 'R8 PHOSPHO ALPHA SYNUCLEIN.tif' -m 30 -o AZ135.ome.tif

**Comment by jmuhlich** [comment] 2022-07-13 14:53
Ashlar is designed to register _tiled_ input images, not whole-slide images. It could technically work with whole-slide images (it will skip the stitching and just perform registration), but there are probably places where the memory usage will be very high for such large images. Could you describe what kind of images these are and how they were acquired?

**Comment by LibbyLi667** [comment] 2022-07-14 02:06
Hi Jeremy. The whole slide images were acquired on a Zeiss Axio Imager Z2 using MetaCyte acquisition software and stitching. The stitched images were exported from Vsviewer software into separate TIFF files per channel.

**Comment by LibbyLi667** [comment] 2022-07-14 02:18
We also have the raw tile images (not stitched) for all the rounds of imaging if that would be easier to work with? 
I am not very familiar with this kind of image files, so not sure if it could work, as the raw images look too many.
